services:
  hubspot_sync:
    restart: unless-stopped
    secrets:
      - HUBSPOT_API_TOKEN
      - EVENT_QUERY
    build:
      context: .
secrets:
  HUBSPOT_API_TOKEN:
    file: secrets/HUBSPOT_API_TOKEN
  EVENT_QUERY:
    file: secrets/EVENT_QUERY